name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure plugin with...
        2. Run Backstage with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please paste relevant configuration (remove sensitive information)
      render: yaml
      placeholder: |
        tyk:
          dashboards:
            - host: http://localhost:3000
              name: development

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you using?
      placeholder: "0.1.13"
    validations:
      required: true

  - type: input
    id: backstage-version
    attributes:
      label: Backstage Version
      description: What version of Backstage are you using?
      placeholder: "1.18.0"
    validations:
      required: true

  - type: input
    id: tyk-version
    attributes:
      label: Tyk Version
      description: What version of Tyk Dashboard are you using?
      placeholder: "5.0.0"

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: "18.x"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please paste any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, links, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
