---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tyk
  description: Tyk API Management
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tyk-dashboard
  title: Tyk Dashboard
  links:
    - url: http://tyk-dashboard.localhost:3000
      title: Tyk Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: guests
  system: tyk
  providesApis:
    - tyk-dashboard-api
    - tyk-dashboard-admin-api
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tyk-gateway
  title: Tyk Gateway
spec:
  type: service
  lifecycle: production
  owner: guests
  system: tyk
  providesApis:
    - tyk-gateway-api
  dependsOn: 
    - conponent:tyk-dashboard
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tyk-dashboard-api
  title: Tyk Dashboard API
spec:
  type: http
  lifecycle: production
  owner: guests
  system: tyk
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Tyk Dashboard API
    servers:
      - url: http://tyk-dashboard.localhost:3000/api
    paths:
      /apis:
        get:
          summary: List all APIs
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tyk-dashboard-admin-api
  title: Tyk Dashboard Admin API
spec:
  type: http
  lifecycle: production
  owner: guests
  system: tyk
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Tyk Dashboard Admin API
    servers:
      - url: http://tyk-dashboard.localhost:3000/admin
    paths:
      /organisations:
        get:
          summary: List all Organisations
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tyk-gateway-api
  title: Tyk Gateway API
spec:
  type: http
  lifecycle: production
  owner: guests
  system: tyk
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Tyk Gateway API
    servers:
      - url: http://tyk-gateway.localhost:8080/tyk
    paths:
      /keys:
        get:
          summary: List all keys